services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    environment:
      MQTT_ADDRESS: mqtt://sjdonado:local_12345@mqtt:1883
    ports:
      - 3000:3000
    depends_on:
      - mqtt
  mqtt:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
      args:
        MQTT_USERNAME: sjdonado
        MQTT_PASSWORD: local_12345
    volumes:
      - mosquitto_data:/mosquitto/data
    ports:
      - 1883:1883

volumes:
  mosquitto_data:
